// Generated by CoffeeScript 1.4.0
(function() {
  var BaseEnv, Environment, baseEnv, fs, loglet,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Environment = require('./environment');

  loglet = require('loglet');

  fs = require('fs');

  BaseEnv = (function(_super) {

    __extends(BaseEnv, _super);

    function BaseEnv() {
      return BaseEnv.__super__.constructor.apply(this, arguments);
    }

    return BaseEnv;

  })(Environment);

  baseEnv = new BaseEnv();

  baseEnv.define('+', function(a, b) {
    return a + b;
  });

  baseEnv.define('-', function(a, b) {
    return a - b;
  });

  baseEnv.define('*', function(a, b) {
    return a * b;
  });

  baseEnv.define('%', function(a, b) {
    return a % b;
  });

  baseEnv.define('>', function(a, b) {
    return a > b;
  });

  baseEnv.define('>=', function(a, b) {
    return a >= b;
  });

  baseEnv.define('<=', function(a, b) {
    return a <= b;
  });

  baseEnv.define('<', function(a, b) {
    return a < b;
  });

  baseEnv.define('==', function(a, b) {
    return a === b;
  });

  baseEnv.define('!=', function(a, b) {
    return a !== b;
  });

  baseEnv.define('isNumber', function(a) {
    return typeof a === 'number' || a instanceof Number;
  });

  module.exports = baseEnv;

}).call(this);
