// Generated by CoffeeScript 1.4.0
(function() {
  var DataStack;

  DataStack = (function() {

    function DataStack() {
      this.inner = [];
    }

    DataStack.prototype.top = function() {
      this._assertNotEmpty();
      return this.inner[this.inner.length - 1];
    };

    DataStack.prototype.push = function(data) {
      return this.inner.push(data);
    };

    DataStack.prototype._assertNotEmpty = function() {
      if (this.inner.length === 0) {
        throw {
          error: 'stack_underflow'
        };
      }
    };

    DataStack.prototype.pop = function() {
      this._assertNotEmpty();
      return this.inner.pop();
    };

    return DataStack;

  })();

}).call(this);
