// Generated by CoffeeScript 1.4.0
(function() {
  var AST, Environment, TR, compile, escodegen, esnode, get, register, types, util, _array, _assign, _binary, _block, _catch, _compile, _define, _export, _finally, _funcall, _if, _import, _importBinding, _importID, _importSpec, _literal, _local, _member, _module, _null, _number, _object, _param, _procedure, _proxyval, _ref, _return, _symbol, _task, _throw, _toplevel, _try, _undefined,
    __slice = [].slice;

  escodegen = require('escodegen');

  esnode = require('./esnode');

  AST = require('./ast');

  util = require('./util');

  TR = require('./trace');

  types = {};

  register = function(ast, compiler) {
    if (types.hasOwnProperty(ast.type)) {
      throw new Error("compiler:duplicate_type: " + ast.type);
    }
    return types[ast.type] = compiler;
  };

  get = function(ast) {
    if (types.hasOwnProperty(ast.type())) {
      return types[ast.type()];
    } else {
      throw new Error("compiler:unknown_type: " + (ast.type()));
    }
  };

  Environment = (function() {

    function Environment(prev) {
      this.prev = prev != null ? prev : null;
      this.inner = {};
    }

    Environment.prototype._has = function(key) {};

    return Environment;

  })();

  compile = function(ast) {
    var node;
    node = _compile(ast);
    return '(' + escodegen.generate(node) + ')';
  };

  _compile = function(ast, env, res) {
    var compiler;
    compiler = get(ast);
    return compiler(ast);
  };

  _literal = function(ast) {
    return esnode.literal(ast.value);
  };

  register(AST.get('string'), _literal);

  register(AST.get('bool'), _literal);

  _number = function(ast) {
    if (ast.value < 0) {
      return esnode.unary('-', esnode.literal(-ast.value));
    } else {
      return esnode.literal(ast.value);
    }
  };

  register(AST.get('number'), _number);

  _null = function(ast) {
    return esnode.null_();
  };

  register(AST.get('null'), _null);

  _undefined = function(ast) {
    return esnode.undefined_();
  };

  register(AST.get('unit'), _undefined);

  _member = function(ast) {
    var head, key;
    head = _compile(ast.head);
    key = ast.key.type() === 'symbol' ? esnode.literal(ast.key.value) : _compile(ast.key);
    return esnode.funcall(esnode.member(esnode.identifier('_rt'), esnode.identifier('member')), [head, key]);
  };

  register(AST.get('member'), _member);

  _symbol = function(ast) {
    return esnode.identifier(ast.value);
  };

  register(AST.get('symbol'), _symbol);

  _object = function(ast) {
    var key, val;
    return esnode.object((function() {
      var _i, _len, _ref, _ref1, _results;
      _ref = ast.value;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _ref1 = _ref[_i], key = _ref1[0], val = _ref1[1];
        _results.push([key, _compile(val)]);
      }
      return _results;
    })());
  };

  register(AST.get('object'), _object);

  _array = function(ast) {
    var item;
    return esnode.array((function() {
      var _i, _len, _ref, _results;
      _ref = ast.value;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        _results.push(_compile(item));
      }
      return _results;
    })());
  };

  register(AST.get('array'), _array);

  _block = function(ast) {
    var item;
    return esnode.block((function() {
      var _i, _len, _ref, _results;
      _ref = ast.items;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        _results.push(_compile(item));
      }
      return _results;
    })());
  };

  register(AST.get('block'), _block);

  _assign = function(ast) {
    return esnode.assign(_compile(ast.name), _compile(ast.value));
  };

  register(AST.get('assign'), _assign);

  _define = function(ast) {
    var id, name, value;
    name = (function() {
      switch (ast.name.type()) {
        case 'ref':
          return esnode.literal(ast.name.name.value);
        case 'symbol':
          return esnode.literal(ast.name.value);
        default:
          throw new Error("escompile.define:unknown_name_type: " + ast.name);
      }
    })();
    value = esnode.funcall(esnode.member(esnode.identifier('_module'), esnode.identifier('define')), [name, _compile(ast.value)]);
    id = (function() {
      switch (ast.name.type()) {
        case 'ref':
          return _compile(ast.name.normalName());
        case 'symbol':
          return _compile(ast.name);
        default:
          throw new Error("escompile.define:unknown_name_type: " + ast.name);
      }
    })();
    return esnode.declare('var', [id, value]);
  };

  register(AST.get('define'), _define);

  _local = function(ast) {
    if (!ast.value) {
      return esnode.declare('var', [_compile(ast.name)]);
    } else {
      return esnode.declare('var', [_compile(ast.name), _compile(ast.value)]);
    }
  };

  register(AST.get('local'), _local);

  _ref = function(ast) {
    if (ast.value.type() === 'proxyval') {
      return _compile(ast.value);
    } else if (this.isDefine) {
      return esnode.funcall(esnode.member(esnode.identifier('_module'), esnode.identifier('get')), [esnode.literal(ast.name.value)]);
    } else {
      return _compile(ast.name);
    }
  };

  register(AST.get('ref'), _ref);

  _proxyval = function(ast) {
    var res;
    res = typeof ast.compiler === 'function' || ast.compiler instanceof Function ? ast.compiler() : ast.compiler instanceof AST ? _compile(ast.compiler) : _compile(ast.name);
    return res;
  };

  register(AST.get('proxyval'), _proxyval);

  _param = function(ast) {
    return _compile(ast.name);
  };

  register(AST.get('param'), _param);

  _procedure = function(ast) {
    var func, maker, name, param;
    name = ast.name ? _compile(ast.name) : null;
    func = esnode["function"](name, (function() {
      var _i, _len, _ref1, _results;
      _ref1 = ast.params;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        param = _ref1[_i];
        _results.push(_compile(param));
      }
      return _results;
    })(), _compile(ast.body));
    maker = esnode.member(esnode.identifier('_rt'), esnode.identifier('proc'));
    return esnode.funcall(maker, [func]);
  };

  register(AST.get('procedure'), _procedure);

  _task = function(ast) {
    var name, param;
    name = ast.name ? _compile(ast.name) : null;
    return esnode["function"](name, (function() {
      var _i, _len, _ref1, _results;
      _ref1 = ast.params;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        param = _ref1[_i];
        _results.push(_compile(param));
      }
      return _results;
    })(), _compile(ast.body));
  };

  register(AST.get('task'), _task);

  _if = function(ast) {
    return esnode["if"](_compile(ast.cond), _compile(ast.then), _compile(ast["else"]));
  };

  register(AST.get('if'), _if);

  _funcall = function(ast) {
    var arg;
    return esnode.funcall(_compile(ast.funcall), (function() {
      var _i, _len, _ref1, _results;
      _ref1 = ast.args;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        arg = _ref1[_i];
        _results.push(_compile(arg));
      }
      return _results;
    })());
  };

  register(AST.get('funcall'), _funcall);

  register(AST.get('taskcall'), _funcall);

  _return = function(ast) {
    return esnode["return"](_compile(ast.value));
  };

  register(AST.get('return'), _return);

  _binary = function(ast) {
    return esnode.binary(ast.op, _compile(ast.lhs), _compile(ast.rhs));
  };

  register(AST.get('binary'), _binary);

  _throw = function(ast) {
    return esnode["throw"](_compile(ast.value));
  };

  register(AST.get('throw'), _throw);

  _catch = function(ast) {
    return esnode["catch"](_compile(ast.param), _compile(ast.body));
  };

  _finally = function(ast) {
    return _compile(ast);
  };

  _try = function(ast) {
    var exp;
    return esnode["try"](_compile(ast.body), (function() {
      var _i, _len, _ref1, _results;
      _ref1 = ast.catches;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        exp = _ref1[_i];
        _results.push(_catch(exp));
      }
      return _results;
    })(), ast["finally"] ? _finally(ast["finally"]) : null);
  };

  register(AST.get('try'), _try);

  _toplevel = function(ast) {
    var imp, imports, params, proc;
    imports = esnode.array((function() {
      var _i, _len, _ref1, _results;
      _ref1 = ast.imports;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        imp = _ref1[_i];
        _results.push(_importSpec(imp));
      }
      return _results;
    })());
    params = [_compile(ast.moduleParam)].concat((function() {
      var _i, _len, _ref1, _results;
      _ref1 = ast.imports;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        imp = _ref1[_i];
        _results.push(_importID(imp));
      }
      return _results;
    })()).concat([_compile(ast.callbackParam)]);
    proc = esnode["function"](null, params, _compile(ast.body));
    return esnode.funcall(esnode.member(esnode.identifier('_rt'), esnode.identifier('toplevel')), [imports, proc]);
  };

  register(AST.get('toplevel'), _toplevel);

  _module = function(ast) {
    var imp, imports, params, proc;
    imports = esnode.array((function() {
      var _i, _len, _ref1, _results;
      _ref1 = ast.imports;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        imp = _ref1[_i];
        _results.push(_importSpec(imp));
      }
      return _results;
    })());
    params = [_compile(ast.moduleParam)].concat((function() {
      var _i, _len, _ref1, _results;
      _ref1 = ast.imports;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        imp = _ref1[_i];
        _results.push(_importID(imp));
      }
      return _results;
    })()).concat([_compile(ast.callbackParam)]);
    proc = esnode["function"](null, params, _compile(ast.body));
    return esnode.funcall(esnode.member(esnode.identifier('_rt'), esnode.identifier('module')), [_compile(ast.spec), imports, proc]);
  };

  register(AST.get('module'), _module);

  _importSpec = function(ast) {
    return _compile(ast.spec);
  };

  _importID = function(ast) {
    return _compile(ast.idParam);
  };

  _importBinding = function(ast, binding) {
    return [_compile(binding.as), esnode.member(_importID(ast), _compile(binding.spec))];
  };

  _import = function(ast) {
    var binding;
    return esnode.declare.apply(esnode, ['var'].concat(__slice.call((function() {
      var _i, _len, _ref1, _results;
      _ref1 = ast.bindings;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        binding = _ref1[_i];
        _results.push(_importBidning(ast, binding));
      }
      return _results;
    })())));
  };

  register(AST.get('import'), _import);

  _export = function(ast) {
    var binding, bindings;
    bindings = (function() {
      var _i, _len, _ref1, _results;
      _ref1 = ast.bindings;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        binding = _ref1[_i];
        _results.push(esnode.funcall(esnode.member(esnode.identifier('_module'), esnode.identifier('export')), [esnode.literal(binding.spec.value)]));
      }
      return _results;
    })();
    return esnode.block(bindings);
  };

  register(AST.get('export'), _export);

  module.exports = {
    compile: compile,
    register: register,
    get: get
  };

}).call(this);
