// Generated by CoffeeScript 1.4.0
(function() {
  var Promise, registerAsync, registerSync;

  Promise = require('./promise');

  registerAsync = function(proc) {
    proc = Promise.nodeify(proc);
    return proc.__vmlet = {
      async: true
    };
  };

  registerSync = function(proc) {
    return proc.__vmlet = {
      sync: true
    };
  };

  module.exports = {
    registerAsync: registerAsync
  };

}).call(this);
