// Generated by CoffeeScript 1.4.0
(function() {
  var CodeBlock, Procedure,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CodeBlock = require('./codeblock');

  Procedure = (function(_super) {

    __extends(Procedure, _super);

    function Procedure(name, parameters, body) {
      this.name = name;
      this.parameters = parameters;
      this.items = body.items;
      this["catch"] = body["catch"];
      this["finally"] = body["finally"];
    }

    return Procedure;

  })(CodeBlock);

  module.exports = Procedure;

}).call(this);
