// Generated by CoffeeScript 1.4.0
(function() {
  var AST, Environment, LambdaLifting;

  Environment = require('./environment');

  AST = require('./ast');

  LambdaLifting = (function() {

    function LambdaLifting() {}

    LambdaLifting.transform = function(ast, env) {
      if (!this.reg) {
        this.reg = new this();
      }
      return this.reg.transform(ast, env);
    };

    LambdaLifting.prototype.transform = function(ast, env) {};

    LambdaLifting.prototype.run = function(ast, env) {};

    LambdaLifting.prototype._number = function(ast, env) {
      return ast;
    };

    LambdaLifting.prototype._string = function(ast, env) {
      return ast;
    };

    LambdaLifting.prototype._bool = function(ast, env) {
      return ast;
    };

    LambdaLifting.prototype._null = function(ast, env) {
      return ast;
    };

    LambdaLifting.prototype._unit = function(ast, env) {
      return ast;
    };

    return LambdaLifting;

  })();

  module.exports = LambdaLifting;

}).call(this);
