// Generated by CoffeeScript 1.4.0
(function() {
  var Lexical;

  Lexical = (function() {

    function Lexical() {
      this.level = 0;
      this.map = {};
    }

    Lexical.prototype.beginScope = function() {};

    Lexical.prototype.endScope = function() {};

    return Lexical;

  })();

  module.exports = Lexical;

}).call(this);
