// Generated by CoffeeScript 1.4.0
(function() {
  var AST, Hashmap, SymbolTable;

  AST = require('./ast');

  Hashmap = require('./hashmap');

  SymbolTable = (function() {

    function SymbolTable(prev) {
      this.prev = prev != null ? prev : null;
      this.dupes = {};
      this.inner = new Hashmap();
    }

    SymbolTable.prototype.has = function(key) {
      if (this.inner.has(key)) {
        return true;
      } else if (this.prev) {
        return this.prev.has(key);
      } else {
        return false;
      }
    };

    SymbolTable.prototype.get = function(key) {
      if (this.inner.has(key)) {
        return this.inner.get(key);
      } else if (this.prev) {
        return this.prev.get(key);
      } else {
        throw new Error("escompile:unknown_identifier: " + key);
      }
    };

    SymbolTable.prototype.alias = function(key) {
      var newKey;
      if (this.has(key)) {
        return this.get(key);
      } else {
        newKey = this.newKey(key);
        this.inner.set(key, newKey);
        return newKey;
      }
    };

    SymbolTable.prototype.newKey = function(key) {
      var name;
      name = key.value;
      if (!this.dupes.hasOwnProperty(name)) {
        this.dupes[name] = 0;
      } else {
        this.dupes[name]++;
      }
      if (this.dupes[name] === 0) {
        return AST.symbol(name);
      } else {
        return AST.symbol("" + name + "$" + this.dupes[name]);
      }
    };

    return SymbolTable;

  })();

  module.exports = SymbolTable;

}).call(this);
