// Generated by CoffeeScript 1.4.0
(function() {
  var AST, transform;

  AST = require('./ast');

  transform = function(ast) {
    console.log('TRE.transform', ast);
    return ast;
  };

  module.exports = {
    transform: transform
  };

}).call(this);
